# Copyright 2026 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName = "service-configuration-admin-frontend"
play.http.router = prod.Routes

play.filters.enabled += play.filters.csp.CSPFilter

play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"
play.modules.enabled += "uk.gov.hmrc.internalauth.client.modules.InternalAuthModule"
play.modules.enabled += "uk.gov.hmrc.serviceconfigurationadminfrontend.Module"

# Custom error handler
play.http.errorHandler = "uk.gov.hmrc.serviceconfigurationadminfrontend.config.ErrorHandler"

features {
  environment = Local
}

urls {
  login-url = "http://localhost:8471/test-only/sign-in"
  continue-url = "http://localhost:11401/service-configuration-admin-frontend/index"
}

microservice {
  services {
    contact-frontend {
      protocol = http
      host = localhost
      port = 9250
    }

    internal-auth {
      protocol = http
      host = localhost
      port = 8470
    }

  }
}

play.i18n.langCookieHttpOnly: "true"

# Change this value to true to enable Welsh translations to be loaded from messages.cy, and to display the language toggle
features.welsh-language-support = false

# Replace play.i18n.langs with the commented out line below when your service has been fully translated into Welsh
# to enable Welsh translations for all content, including the standard headers and footers.
# play.i18n.langs = ["en", "cy"]
play.i18n.langs = ["en"]


